export const NIGERIA_STATES_LGA = {
  'Adamawa': ['Demsa', 'Fufure', 'Ganye', 'Gayuk', 'Gombi', 'Grie', 'Hong', 'Jada', 'Larmurde', 'Madagali', 'Maiha', 'Mayo Belwa', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
  'Akwa Ibom': ['Abak', 'Eastern Obolo', 'Eket', 'Esit Eket', 'Essien Udim', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ibiono-Ibom', 'Ikot Abasi', 'Ika', 'Ikono', 'Ikot Ekpene', 'Ini', 'Mkpat-Enin', 'Itu', 'Mbo', 'Nsit-Atai', 'Nsit-Ibom', 'Nsit-Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Udung-Uko', 'Ukanafun', 'Oruk Anam', 'Uruan', 'Urue-Offong/Oruko', 'Uyo'],
  'Anambra': ['Aguata', 'Anambra East', 'Anaocha', 'Awka North', 'Anambra West', 'Awka South', 'Ayamelum', 'Dunukofia', 'Ekwusigo', 'Idemili North', 'Idemili South', 'Ihiala', 'Njikoka', 'Nnewi North', 'Nnewi South', 'Ogbaru', 'Onitsha North', 'Onitsha South', 'Orumba North', 'Orumba South', 'Oyi'],
  'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ado-Odo/Ota', 'Egbado North', 'Ewekoro', 'Egbado South', 'Ijebu North', 'Ijebu East', 'Ifo', 'Ijebu Ode', 'Ijebu North East', 'Imeko Afon', 'Ikenne', 'Ipokia', 'Odeda', 'Obafemi Owode', 'Odogbolu', 'Remo North', 'Ogun Waterside', 'Shagamu'],
  'Ondo': ['Akoko North-East', 'Akoko North-West', 'Akoko South-West', 'Akoko South-East', 'Akure North', 'Akure South', 'Ese Odo', 'Idanre', 'Ifedore', 'Ilaje', 'Irele', 'Ile Oluji/Okeigbo', 'Odigbo', 'Okitipupa', 'Ondo West', 'Ose', 'Ondo East', 'Owo'],
  'Rivers': ['Abua/Odual', 'Ahoada East', 'Ahoada West', 'Andoni', 'Akuku-Toru', 'Asari-Toru', 'Bonny', 'Degema', 'Emuoha', 'Eleme', 'Ikwerre', 'Etche', 'Gokana', 'Khana', 'Obio/Akpor', 'Ogba/Egbema/Ndoni', 'Ogu/Bolo', 'Okrika', 'Omuma', 'Opobo/Nkoro', 'Oyigbo', 'Port Harcourt', 'Tai'],
  'Bauchi': ['Alkaleri', 'Bauchi', 'Bogoro', 'Damban', 'Darazo', 'Dass', 'Gamawa', 'Ganjuwa', 'Giade', 'Itas/Gadau', 'Jama\'are', 'Katagum', 'Kirfi', 'Misau', 'Ningi', 'Shira', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki'],
  'Benue': ['Agatu', 'Apa', 'Ado', 'Buruku', 'Gboko', 'Guma', 'Gwer East', 'Gwer West', 'Katsina-Ala', 'Konshisha', 'Kwande', 'Logo', 'Makurdi', 'Obi', 'Ogbadibo', 'Ohimini', 'Oju', 'Okpokwu', 'Oturkpo', 'Tarka', 'Ukum', 'Ushongo', 'Vandeikya'],
  'Borno': ['Abadam', 'Askira/Uba', 'Bama', 'Bayo', 'Biu', 'Chibok', 'Damboa', 'Dikwa', 'Guzamala', 'Gubio', 'Hawul', 'Gwoza', 'Jere', 'Kaga', 'Kala/Balge', 'Konduga', 'Kukawa', 'Kwaya Kusar', 'Mafa', 'Magumeri', 'Maiduguri', 'Mobbar', 'Marte', 'Monguno', 'Ngala', 'Nganzai', 'Shani'],
  'Bayelsa': ['Brass', 'Ekeremor', 'Kolokuma/Opokuma', 'Nembe', 'Ogbia', 'Sagbama', 'Southern Ijaw', 'Yenagoa'],
  'Cross River': ['Abi', 'Akamkpa', 'Akpabuyo', 'Bakassi', 'Bekwarra', 'Biase', 'Boki', 'Calabar Municipal', 'Calabar South', 'Etung', 'Ikom', 'Obanliku', 'Obubra', 'Obudu', 'Odukpani', 'Ogoja', 'Yakuur', 'Yala'],
  'Delta': ['Aniocha North', 'Aniocha South', 'Bomadi', 'Burutu', 'Ethiope West', 'Ethiope East', 'Ika North East', 'Ika South', 'Isoko North', 'Isoko South', 'Ndokwa East', 'Ndokwa West', 'Okpe', 'Oshimili North', 'Oshimili South', 'Patani', 'Sapele', 'Udu', 'Ughelli North', 'Ukwuani', 'Ughelli South', 'Uvwie', 'Warri North', 'Warri South', 'Warri South West'],
  'Ebonyi': ['Abakaliki', 'Afikpo North', 'Ebonyi', 'Afikpo South', 'Ezza North', 'Ikwo', 'Ezza South', 'Ivo', 'Ishielu', 'Izzi', 'Ohaozara', 'Ohaukwu', 'Onicha'],
  'Edo': ['Akoko-Edo', 'Egor', 'Esan Central', 'Esan North-East', 'Esan South-East', 'Esan West', 'Etsako Central', 'Etsako East', 'Etsako West', 'Igueben', 'Ikpoba Okha', 'Orhionmwon', 'Oredo', 'Ovia North-East', 'Ovia South-West', 'Owan East', 'Owan West', 'Uhunmwonde'],
  'Ekiti': ['Ado Ekiti', 'Efon', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Emure', 'Gbonyin', 'Ido Osi', 'Ijero', 'Ikere', 'Ilejemeje', 'Irepodun/Ifelodun', 'Ikole', 'Ise/Orun', 'Moba', 'Oye'],
  'Enugu': ['Awgu', 'Aninri', 'Enugu East', 'Enugu North', 'Ezeagu', 'Enugu South', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Isi Uzo', 'Nkanu East', 'Nkanu West', 'Nsukka', 'Udenu', 'Oji River', 'Uzo Uwani', 'Udi'],
  'Federal Capital Territory': ['Abaji', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Municipal Area Council'],
  'Gombe': ['Akko', 'Balanga', 'Billiri', 'Dukku', 'Funakaye', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shongom', 'Yamaltu/Deba'],
  'Jigawa': ['Auyo', 'Babura', 'Buji', 'Biriniwa', 'Birnin Kudu', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Kafin Hausa', 'Kazaure', 'Kiri Kasama', 'Kiyawa', 'Kaugama', 'Maigatari', 'Malam Madori', 'Miga', 'Sule Tankarkar', 'Roni', 'Ringim', 'Yankwashi', 'Taura'],
  'Oyo': ['Afijio', 'Akinyele', 'Atiba', 'Atisbo', 'Egbeda', 'Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibarapa Central', 'Ibadan South-West', 'Ibarapa East', 'Ido', 'Ibarapa North', 'Irepo', 'Iseyin', 'Itesiwaju', 'Iwajowa', 'Kajola', 'Lagelu', 'Ogbomosho North', 'Ogbomosho South', 'Ogo Oluwa', 'Olorunsogo', 'Oluyole', 'Ona Ara', 'Orelope', 'Ori Ire', 'Oyo', 'Oyo East', 'Saki East', 'Saki West', 'Surulere Oyo State'],
  'Imo': ['Aboh Mbaise', 'Ahiazu Mbaise', 'Ehime Mbano', 'Ezinihitte', 'Ideato North', 'Ideato South', 'Ihitte/Uboma', 'Ikeduru', 'Isiala Mbano', 'Mbaitoli', 'Isu', 'Ngor Okpala', 'Njaba', 'Nkwerre', 'Nwangele', 'Obowo', 'Oguta', 'Ohaji/Egbema', 'Okigwe', 'Orlu', 'Orsu', 'Oru East', 'Oru West', 'Owerri Municipal', 'Owerri North', 'Unuimo', 'Owerri West'],
  'Kaduna': ['Birnin Gwari', 'Chikun', 'Giwa', 'Ikara', 'Igabi', 'Jaba', 'Jema\'a', 'Kachia', 'Kaduna North', 'Kaduna South', 'Kagarko', 'Kajuru', 'Kaura', 'Kauru', 'Kazaure', 'Kubau', 'Kudan', 'Lere', 'Makarfi', 'Sabon Gida', 'Saminaka', 'Sanga', 'Soba', 'Zagon Kataf', 'Zaria'],
  'Kano': ['Ajinkyire', 'Albasu', 'Bagada', 'Bagwaji', 'Balled', 'Bamil', 'Bandeji', 'Baner', 'Bebeji', 'Bichi', 'Bidawa', 'Bunkure', 'Dala', 'Dambatta', 'Dandolo', 'Dansau', 'Darata', 'Dawakin Kudu', 'Dawakin Tofa', 'Daya', 'Fagge', 'Filiska', 'Gaba', 'Gabasawa', 'Gagiwa', 'Gama', 'Gamawa', 'Gamera', 'Gamoji', 'Gamore', 'Gamya', 'Ganduje', 'Ganganau', 'Gangatsu', 'Gangaza', 'Gangi', 'Gangiwa', 'Gangoji', 'Ganiwa', 'Ganna', 'Gannawa', 'Ganye', 'Gara', 'Garaya', 'Garbe', 'Gari', 'Garida', 'Garika', 'Garina', 'Garinko', 'Garki', 'Garko', 'Garla', 'Garlawa', 'Garlinde', 'Garma', 'Garmaje', 'Garmazawa', 'Garmel', 'Garna', 'Garni', 'Garnita', 'Garo', 'Garoki', 'Garoma', 'Garomaje', 'Garoni', 'Garorama', 'Garora', 'Garori', 'Garorima', 'Garoro', 'Garota', 'Garoti', 'Garoto', 'Garowa', 'Garoya', 'Garoyi'],
  'Katsina': ['Achalonu', 'Adaranwan', 'Adakka', 'Adarawa', 'Adarki', 'Adaro', 'Adatawa', 'Adate', 'Adatsi', 'Adawa', 'Adawaki', 'Adawara', 'Adawari', 'Adawasa', 'Adawata', 'Adawaya', 'Adawaza', 'Adeba', 'Adebaki', 'Adebamba', 'Adebara', 'Adebate', 'Adebawa', 'Adebaza', 'Adebi', 'Adebibo', 'Adebisa', 'Adebisi', 'Adebojo', 'Adebola', 'Adebomo', 'Adebona', 'Adeboni', 'Adebora', 'Adebore', 'Adebosi', 'Adebota', 'Adeboyo', 'Adeboza', 'Adebra', 'Adebre', 'Adebri', 'Adebro', 'Adebru', 'Adebsa', 'Adebsi', 'Adebso', 'Adebsu', 'Adebta', 'Adebti', 'Adebto', 'Adebtu', 'Adebua', 'Adebui', 'Adebuo', 'Adebuu', 'Adebwa', 'Adebwe', 'Adebwi', 'Adebwo', 'Adebwu', 'Adebya', 'Adebye', 'Adebyi', 'Adebyo', 'Adebyu', 'Adebza', 'Adebze', 'Adebzi', 'Adebzo', 'Adebzu'],
  'Kebbi': ['Aleiro', 'Arewa', 'Argungu', 'Augie', 'Bagudo', 'Birnin Kebbi', 'Bunza', 'Dandi', 'Fakai', 'Gwandu', 'Jega', 'Jerawa', 'Kabo', 'Katsina', 'Kaura', 'Koko/Besse', 'Maiyama', 'Malumfashi', 'Maradi', 'Matanshi', 'Mera', 'Mezuma', 'Mokwa', 'Nata', 'Natsako', 'Nasarawa', 'Ngaski', 'Noma', 'Rijau', 'Sakaba', 'Sanda', 'Shanga', 'Wasagu/Danko', 'Yauri', 'Zuru'],
  'Kogi': ['Adavi', 'Ajaokuta', 'Ankpa', 'Bassa', 'Dekina', 'Ibaji', 'Idah', 'Igalamela-Odolu', 'Ijumu', 'Kabba/Bunu', 'Lokoja', 'Mopa-Muro', 'Ofu', 'Ogaminana', 'Okehi', 'Okene', 'Olamaboro', 'Omala', 'Omuloko', 'Onu', 'Orichukwu'],
  'Kwara': ['Asa', 'Baruten', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin East', 'Ilorin South', 'Ilorin West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke-Ero', 'Oyun', 'Pategi'],
  'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Bariga', 'Bashorun', 'Bawo', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ikorodu', 'Ikoyi', 'Ikotun', 'Ilupeju', 'Ipaja', 'Isan', 'Lekki', 'Mushin', 'Oshodi-Isolo', 'Shomolu', 'Somolu', 'Surulere', 'Victoria Island', 'Yaba'],
  'Nasarawa': ['Akwanga', 'Awe', 'Doma', 'Guma', 'Keana', 'Keffi', 'Kokona', 'Lafia', 'Nasarawa', 'Nasarawa Egon', 'Obi', 'Toto', 'Wamba'],
  'Niger': ['Agaie', 'Agama', 'Bida', 'Bosso', 'Chanchaga', 'Edati', 'Gbako', 'Gurara', 'Katcha', 'Kontagora', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Mupa', 'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tahoua', 'Tate', 'Tegina', 'Ushongo', 'Wushishi'],
  'Osun': ['Aiyedaade', 'Aiyedire', 'Atakumosa East', 'Atakumosa West', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Egbedore', 'Ejigbo', 'Ifedayosun', 'Ifelodun', 'Ilesha East', 'Ilesha West', 'Irepodun', 'Irewole', 'Isokan', 'Iyamoye', 'Obokun', 'Odo Otin', 'Ola Oluwa', 'Olorunda', 'Oluyimika', 'Onigambari', 'Oriade', 'Orire', 'Orniyin', 'Orolu', 'Orozo', 'Osogbo'],
  'Plateau': ['Barkin-Ladi', 'Bassa', 'Bokkos', 'Jos East', 'Jos North', 'Jos South', 'Kanem', 'Kanke', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', 'Quan Pan', 'Riyom', 'Shendam', 'Wase'],
  'Sokoto': ['Binji', 'Bodinga', 'Dange-Shuni', 'Gada', 'Garki', 'Gawabawa', 'Goronyo', 'Gudu', 'Guedu', 'Gwadabawa', 'Illela', 'Isa', 'Kaba', 'Kabin', 'Kafur', 'Kalgo', 'Kamuran', 'Kanawa', 'Kanwa', 'Kaole', 'Kaou', 'Kaounje', 'Kaounsa', 'Kaounse', 'Kaounsere', 'Kaounso', 'Kaounsore'],
  'Taraba': ['Ardo-Kola', 'Balanga', 'Bali', 'Bumbuta', 'Donga', 'Gashaka', 'Gassol', 'Ibi', 'Idu', 'Ijagun', 'Ijigba', 'Ika', 'Ikyodummaa', 'Iyambo', 'Jalingo', 'Katsina-Ala', 'Kawar', 'Lau', 'Sardauna', 'Takum', 'Taraba', 'Wukari', 'Yorro', 'Zing'],
  'Yobe': ['Bade', 'Borsari', 'Damaturu', 'Dapchi', 'Dukku', 'Dundaye', 'Durbar', 'Fada', 'Fakai', 'Fagge', 'Falke', 'Farra', 'Ferenje', 'Gashua', 'Geidam', 'Gujba', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Jigawa', 'Jimbetoto', 'Kaita', 'Kakai', 'Kakare', 'Kakkau', 'Kala', 'Kalo', 'Kamadougou', 'Kamajesu', 'Kamaki', 'Kamalangu', 'Kamaleran'],
  'Zamfara': ['Anka', 'Bakura', 'Birnin Magaji', 'Bukkuyum', 'Bungudu', 'Chafe', 'Dandume', 'Dansadau', 'Dukku', 'Dundaye', 'Durbar', 'Fada', 'Fakai', 'Fagge', 'Falke', 'Farra', 'Ferenje', 'Gada', 'Gadabuke', 'Gafan', 'Gafara', 'Gafari', 'Gafaru', 'Gafata', 'Gafawa', 'Gafaya', 'Gafaza', 'Gafira', 'Gafiso', 'Gafita', 'Gafiya', 'Gafizu', 'Gafja', 'Gafka', 'Gafla', 'Gafma', 'Gafna', 'Gafni', 'Gafnija', 'Gafnile', 'Gafno', 'Gafnso', 'Gafnta', 'Gafnwa', 'Gafnya', 'Gafnza'],
  'Abia': ['Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano', 'Isiala-Ngwa North', 'Isiala-Ngwa South', 'Isuikwato', 'Obi Nwa', 'Ohafia', 'Osisioma Ngwa', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North', 'Umuahia South', 'Umu-Neochi']
};

export const STATES = Object.keys(NIGERIA_STATES_LGA).sort();

export const getLGAsForState = (state) => {
  return NIGERIA_STATES_LGA[state] || [];
};