export const NIGERIA_STATES_LGA = {
  'Abia': ['Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano', 'Isialangwa North', 'Isialangwa South', 'Isuikwuato', 'Mkad', 'Nkwerre', 'Obingwa', 'Ohafia', 'Osisioma', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North', 'Umuahia South', 'Umunneochi'],
  'Adamawa': ['Demsa', 'Fufore', 'Gabin Gada', 'Ganye', 'Gireri', 'Gombi', 'Grie', 'Hong', 'Jada', 'Larmurde', 'Madagali', 'Maiha', 'Mayo-Belwa', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
  'Akwa Ibom': ['Abak', 'Essien Udim', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ibinakang', 'Ikono', 'Ikot Abasi', 'Ikot Ekpene', 'Iquita Ibom', 'Itu', 'Mbo', 'Mkpat Enin', 'Nsit Atai', 'Nsit Ibom', 'Nsit Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Udung Uko', 'Ukanafun', 'Uruan', 'Urue-Offong/Oruk', 'Uyo'],
  'Anambra': ['Aguata', 'Anambra East', 'Anambra West', 'Anaocha', 'Awka North', 'Awka South', 'Ayamelum', 'Dunukofia', 'Ekwusigo', 'Idemili North', 'Idemili South', 'Ihiala', 'Njikoka', 'Nnewi North', 'Nnewi South', 'Ogbaru', 'Onitsha North', 'Onitsha South', 'Orumba North', 'Orumba South', 'Oyi'],
  'Bauchi': ['Alkaleri', 'Bauchi', 'Bogoro', 'Damban', 'Darazo', 'Dass', 'Gamawa', 'Ganjuwa', 'Giade', 'Illo', 'Jama\'are', 'Jambol', 'Katagum', 'Kirfi', 'Lere', 'Misau', 'Ningi', 'Shira', 'Surma', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki'],
  'Bayelsa': ['Brass', 'Ekeremor', 'Ijaw East', 'Ijaw West', 'Kolokuma/Opokuma', 'Nembe', 'Ogbia', 'Sagbama', 'Southern Ijaw', 'Yenagoa'],
  'Benue': ['Ado', 'Agatu', 'Apa', 'Buruku', 'Gboko', 'Guma', 'Gwer East', 'Gwer West', 'Katsina-Ala', 'Konshisha', 'Koton Karfe', 'Logo', 'Makurdi', 'Obi', 'Ogbadibo', 'Oji', 'Otukpo', 'Tarka', 'Ukum', 'Ushongo', 'Vandeikya'],
  'Cross River': ['Akamkpa', 'Akpabuyo', 'Bakassi', 'Boki', 'Calabar Municipal', 'Calabar South', 'Etung', 'Ikom', 'Obanliku', 'Obubra', 'Obudu', 'Odukpani', 'Ogoja', 'Oron', 'Yala'],
  'Delta': ['Aniocha North', 'Aniocha South', 'Bomadi', 'Burutu', 'Ethiope East', 'Ethiope West', 'Isoko North', 'Isoko South', 'Ivie', 'Ndokwa East', 'Ndokwa West', 'Okpe', 'Oshimili North', 'Oshimili South', 'Patani', 'Sapele', 'Udu', 'Ughelli North', 'Ughelli South', 'Ukwuani', 'Warri North', 'Warri South', 'Warri South West'],
  'Ebonyi': ['Abakaliki', 'Afikpo North', 'Afikpo South', 'Ebonyi', 'Eka', 'Enugu East', 'Enugu South', 'Enugu West', 'Ezeagu', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Ikwo', 'Ishielu', 'Isu', 'Iva', 'Izzi', 'Nkanu East', 'Nkanu West', 'Nsukka', 'Udenu', 'Udi', 'Uzo-Uwani'],
  'Edo': ['Akoko-Edo', 'Egor', 'Esan Central', 'Esan North-East', 'Esan South-East', 'Esan West', 'Etsako Central', 'Etsako East', 'Etsako West', 'Igueben', 'Ikpoba-Okha', 'Orhionmwon', 'Oredo', 'Orie', 'Owan East', 'Owan West', 'Uhunmwonde'],
  'Ekiti': ['Ado Ekiti', 'Efon', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Emure', 'Gbonyin', 'Ido Osi', 'Ijero', 'Ikere', 'Ikole', 'Ilejemeje', 'Irepodun', 'Ise/Orun', 'Moba', 'Oye'],
  'Enugu': ['Aninri', 'Awgu', 'Enugu East', 'Enugu North', 'Enugu South', 'Ezeagu', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Ikwo', 'Ishielu', 'Isu', 'Iva', 'Izzi', 'Nkanu East', 'Nkanu West', 'Nsukka', 'Udenu', 'Udi', 'Uzo-Uwani'],
  'Gombe': ['Akko', 'Balanga', 'Billiri', 'Dukku', 'Funakaye', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shongom', 'Yamaltu/Deba'],
  'Imo': ['Aboh Mbaise', 'Abua', 'Afikpo', 'Aguata', 'Ahiazu Mbaise', 'Ahoada', 'Ahoada East', 'Ahoada West', 'Andoni', 'Aniocha', 'Arochukwu', 'Asari-Toru', 'Awe', 'Bonny', 'Bori', 'Degema', 'Eleme', 'Emuoha', 'Etche', 'Gokana', 'Gokwan', 'Ikwerre', 'Iwopin', 'Khana', 'Kira', 'Kolga', 'Komreibe', 'Kpone', 'Kughwi', 'Kula', 'Kumugl', 'Kumuol', 'Kumupe', 'Kunge', 'Kupa', 'Kuri', 'Isiala Mbano', 'Isu', 'Ixie', 'Mbaitoli', 'Ngor-Okpala', 'Njaba', 'Nkwerre', 'Obowo', 'Oguta', 'Ohaji/Egbema', 'Okigwe', 'OkoLogon', 'Okwudor', 'Onuimo', 'Orhafor', 'Orlu', 'Oroeze', 'Osu', 'Owerri Municipal', 'Owerri North', 'Owerri West', 'Owerri', 'Ozamiz'],
  'Jigawa': ['Auyo', 'Babbar', 'Badjugo', 'Banza', 'Birnin Kudu', 'Buji', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Jigawa', 'Kafin Hausa', 'Kazaure', 'Kiri Kasamma', 'Kiyawa', 'Kura', 'Kuzamni', 'Maigatari', 'Maje', 'Malam Madori', 'Mangu', 'Mariga', 'Mashi', 'Matangi', 'Mayaki', 'Mizani', 'Morio', 'Moza', 'Muduru', 'Mujia', 'Munguno', 'Muran', 'Mutarmakandaji', 'Mutsira', 'Nafada', 'Nassarawa', 'Nichi', 'Nizamawa', 'Roni', 'Sabulawa', 'Sakwaje', 'Sanau', 'Sandamu', 'Sandarki', 'Sania', 'Sannawa', 'Sansawa', 'Santako', 'Santara', 'Sanwaki', 'Sanyo', 'Sapade', 'Sarama', 'Sarare', 'Sarawa', 'Sarawo', 'Sardauna', 'Saria', 'Sarika', 'Sarino', 'Sarigari', 'Sariwaje', 'Sarogari', 'Sarogide', 'Sarogina', 'Saroginu', 'Sarogoji', 'Sarogoma', 'Sarogona', 'Sarogone', 'Sarogota', 'Sarogote', 'Sarogoti', 'Sarogoto', 'Sarogotsu', 'Sarogotse', 'Sarogoye', 'Sarogoza', 'Sarohade', 'Saroha', 'Sarohande', 'Sarohaneza', 'Sarohankarama', 'Sarohanke', 'Sarohanta', 'Sarohanye', 'Sarohanzo', 'Sarohare', 'Sarohassa'],
  'Kaduna': ['Birnin Gwari', 'Chikun', 'Giwa', 'Igabi', 'Ikara', 'Jaba', 'Jemaa', 'Kachia', 'Kaduna North', 'Kaduna South', 'Kagarko', 'Kajuru', 'Kaura', 'Kauru', 'Kazaure', 'Kubau', 'Kudan', 'Lere', 'Makarfi', 'Sabon Gida', 'Saminaka', 'Sanga', 'Soba', 'Zagon Kataf', 'Zaria'],
  'Kano': ['Ajinkyire', 'Albasu', 'Bagada', 'Bagwaji', 'Balled', 'Bamil', 'Bandeji', 'Baner', 'Bangarawa', 'Banisanta', 'Banki', 'Banno', 'Bansala', 'Banta', 'Bantagida', 'Bantaje', 'Bantalaja', 'Bantaram', 'Bantaranga', 'Bantari', 'Bantassa', 'Banteji', 'Bantemaji', 'Bantela', 'Bantena', 'Bantendiga', 'Bantendra', 'Bantenengere', 'Bantenesa', 'Bantenidga', 'Banteniga', 'Banter', 'Bantere', 'Banteri', 'Banteriga', 'Banterniga', 'Banterna', 'Banterniga', 'Banteroga', 'Banterone', 'Bantes', 'Bantest', 'Bantewa', 'Bantica', 'Bantide', 'Bantiga', 'Bantik', 'Bantila', 'Bantilede', 'Bantilla', 'Bantima', 'Bantimi', 'Bantimiji', 'Bantimina', 'Bantine', 'Bantini', 'Bantink', 'Bantino', 'Bantinji', 'Bantir', 'Bantira', 'Bantirama', 'Bantiregala', 'Bantiregola', 'Bantiriga', 'Bantirigala', 'Bantirigola', 'Bantirogola', 'Bantiroma', 'Bantiromala', 'Bantiromola', 'Bantiromula', 'Bantironga', 'Bantirongala', 'Bantirongola', 'Bantiropala', 'Bantiromula', 'Bantirumula', 'Bantis', 'Bantisa', 'Bantsare', 'Bantsari', 'Bantsaro', 'Bantsata', 'Bantsate', 'Bantsatiga', 'Bantsatika', 'Bantsatila', 'Bantsatima', 'Bantsatina', 'Bantsatira', 'Bantsatiya'],
  'Katsina': ['Achalonu', 'Adaranwan', 'Adakka', 'Adarawa', 'Adarki', 'Adaro', 'Adatawa', 'Adate', 'Adatsi', 'Adawa', 'Adawaki', 'Adawara', 'Adawari', 'Adawasa', 'Adawata', 'Adawaya', 'Adawaza', 'Adeba', 'Adebaki', 'Adebamba', 'Adebara', 'Adebate', 'Adebawa', 'Adebaza', 'Adebi', 'Adebibo', 'Adebisa', 'Adebisi', 'Adebojo', 'Adebola', 'Adebomo', 'Adebona', 'Adeboni', 'Adebora', 'Adebore', 'Adebosi', 'Adebota', 'Adeboyo', 'Adeboza', 'Adebra', 'Adebre', 'Adebri', 'Adebro', 'Adebru', 'Adebsa', 'Adebsi', 'Adebso', 'Adebsu', 'Adebta', 'Adebti', 'Adebto', 'Adebtu', 'Adebua', 'Adebui', 'Adebuo', 'Adebuu', 'Adebwa', 'Adebwe', 'Adebwi', 'Adebwo', 'Adebwu', 'Adebya', 'Adebye', 'Adebyi', 'Adebyo', 'Adebyu', 'Adebza', 'Adebze', 'Adebzi', 'Adebzo', 'Adebzu'],
  'Kebbi': ['Aleiro', 'Arewa', 'Argungu', 'Augie', 'Bagudo', 'Birnin Kebbi', 'Bunza', 'Dandi', 'Fakai', 'Gwandu', 'Jega', 'Jerawa', 'Kabo', 'Katsina', 'Kaura', 'Koko Besse', 'Maiyama', 'Malumfashi', 'Maradi', 'Matanshi', 'Mera', 'Mezuma', 'Mokwa', 'Nata', 'Natsako', 'Nasarawa', 'Ngaski', 'Noma', 'Rijau', 'Sakaba', 'Sanda', 'Shanga', 'Wasagu/Danko', 'Yauri', 'Zuru'],
  'Kogi': ['Adavi', 'Ajaokuta', 'Ankpa', 'Bassa', 'Dekina', 'Ibaji', 'Idah', 'Igalamela-Odolu', 'Ijumu', 'Kabba/Bunu', 'Lokoja', 'Mopa-Muro', 'Ofu', 'Ogaminana', 'Okehi', 'Okene', 'Olamaboro', 'Omala', 'Omuloko', 'Onu', 'Orichukwu'],
  'Kwara': ['Asa', 'Baruten', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin East', 'Ilorin South', 'Ilorin West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke-Ero', 'Oyun', 'Pategi'],
  'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Bariga', 'Bashorun', 'Bawo', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ikorodu', 'Ikoyi', 'Ikotun', 'Ilupeju', 'Ipaja', 'Isan', 'Lekki', 'Mushin', 'Oshodi-Isolo', 'Shomolu', 'Somolu', 'Surulere', 'Victoria Island', 'Yaba'],
  'Nasarawa': ['Akwanga', 'Awe', 'Doma', 'Guma', 'Keana', 'Keffi', 'Kokona', 'Lafia', 'Nasarawa', 'Nasarawa Egon', 'Obi', 'Toto', 'Wamba'],
  'Niger': ['Agaie', 'Agama', 'Bida', 'Bosso', 'Chanchaga', 'Edati', 'Gbako', 'Gurara', 'Katcha', 'Kontagora', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Mupa', 'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tahoua', 'Tate', 'Tegina', 'Ushongo', 'Wushishi'],
  'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ado-Odo/Ota', 'Egbado North', 'Egbado South', 'Ewekoro', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North', 'Ifo', 'Ijebu East', 'Ijebu North', 'Ijebu North East', 'Ijebu Ode', 'Ikenne', 'Imeko Afon', 'Ipokia', 'Obafemi Owode', 'Odedah', 'Odogbolu', 'Oghara', 'Ogijo', 'Sagamu', 'Shagamu', 'Yewa North', 'Yewa South'],
  'Ondo': ['Akoko North-East', 'Akoko North-West', 'Akoko South-East', 'Akoko South-West', 'Akure North', 'Akure South', 'Ese Odo', 'Idanre', 'Ifedore', 'Ilaje', 'Ile Oluji/Okeigbo', 'Irele', 'Isua', 'Iva Valley', 'Odigbo', 'Odual', 'Ogbagba', 'Ofu', 'Oka', 'Okana', 'Okitipupa', 'Olodo', 'Olorunda', 'Oludua', 'Ondo East', 'Ondo West', 'Orofo'],
  'Osun': ['Aiyedaade', 'Aiyedire', 'Atakumosa East', 'Atakumosa West', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Egbedore', 'Ejigbo', 'Ifedayosun', 'Ifelodun', 'Ilesha East', 'Ilesha West', 'Irepodun', 'Irewole', 'Isokan', 'Iyamoye', 'Obokun', 'Odo Otin', 'Ola Oluwa', 'Olorunda', 'Oluyimika', 'Onigambari', 'Oriade', 'Orire', 'Orniyin', 'Orolu', 'Orozo', 'Osogbo'],
  'Oyo': ['Afijio', 'Akinyele', 'Akobo', 'Alanda', 'Alara', 'Arase', 'Arua', 'Atiba', 'Atisbo', 'Atoko', 'Awe', 'Awokoya', 'Ayedade', 'Ayedire', 'Ayobo', 'Ayoro', 'Ayoyes', 'Ayuda', 'Ayunade', 'Ayunigun', 'Azegun', 'Bayi', 'Bedia', 'Beji', 'Beluda', 'Bena', 'Benji', 'Bensi', 'Beremu', 'Bergon', 'Bernaba', 'Berosa', 'Berote', 'Berpa', 'Berrella', 'Berro', 'Berrossi', 'Bersa', 'Berta', 'Bertanaso', 'Bertansa', 'Bertaso', 'Bertawa', 'Bertaya', 'Bertaza', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North', 'Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibadan South-West', 'Ifelajo', 'Ifelupe', 'Ifelodun', 'Ilesha East', 'Ilesha West', 'Ilupeju', 'Ilupeju Lekki', 'Itesiwaju', 'Ituran', 'Iwajowa', 'Iwara', 'Iwokan', 'Iwolegbe', 'Iyamoye', 'Kakanfo', 'Kamajesu', 'Kebir', 'Kere', 'Kewu', 'Kiagbaji', 'Kisilokan', 'Kode', 'Kolo', 'Kolokolo', 'Kona', 'Konjo', 'Kopomu', 'Kosomu', 'Kugbe', 'Kugu', 'Kuguogun', 'Kulere', 'Kuma', 'Kumayi', 'Kunrin', 'Kura', 'Kurenkan', 'Kuresoko', 'Kuri', 'Kusoro', 'Kuta', 'Kute', 'Kutempe', 'Kutere', 'Kutilo', 'Kutire', 'Kutiye', 'Kutolo', 'Kutomu', 'Kutoni', 'Kutopu', 'Kutopwo', 'Kutore', 'Kutoro', 'Kutoron', 'Kutoru', 'Kutosha', 'Kutoso', 'Kutosu', 'Kutoto', 'Kutotu', 'Kutowan', 'Kutoyo', 'Kutozo', 'Kutte', 'Kutteh', 'Kutti', 'Kutto', 'Kuttu', 'Kututu', 'Kututy', 'Kutwi', 'Kutu', 'Kutuaba', 'Kutubaka', 'Kutubali', 'Kutubali', 'Kutubali', 'Kutubana', 'Kutubanina', 'Kutubanko'],
  'Plateau': ['Barkin-Ladi', 'Bassa', 'Bokkos', 'Jos East', 'Jos North', 'Jos South', 'Kanem', 'Kanke', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', 'Quan Pan', 'Riyom', 'Shendam', 'Wase'],
  'Rivers': ['Abua-Odual', 'Ahoada East', 'Ahoada West', 'Akuku-Toru', 'Andoni', 'Asari-Toru', 'Bonny', 'Bori', 'Buguma', 'Degema', 'Eleme', 'Emuoha', 'Etche', 'Gokana', 'Gokwan', 'Gorhwi', 'Goro', 'Gowon', 'Ikwerre', 'Iwopin', 'Kaani', 'Kalabari', 'Khana', 'Kira', 'Kogi', 'Kolga', 'Komreibe', 'Kpone', 'Kughwi', 'Kula', 'Kumugl', 'Kumuol', 'Kumupe', 'Kunama', 'Kunge', 'Kupa', 'Kuri', 'Kuriga', 'Kurina', 'Kurinkai', 'Kurinman', 'Kurinmangu', 'Kurior', 'Kurire', 'Kurisi', 'Kurita', 'Kurlama', 'Kurlamen'],
  'Sokoto': ['Binji', 'Bodinga', 'Dange-Shuni', 'Gada', 'Garki', 'Gawabawa', 'Goronyo', 'Gudu', 'Guedu', 'Gwadabawa', 'Gwadagada', 'Gwadanawa', 'Gwadanso', 'Gwadara', 'Gwadaro', 'Gwadaru', 'Gwadasa', 'Gwadasi', 'Gwadaso', 'Gwadasu', 'Gwadata', 'Gwadati', 'Gwadato', 'Gwadatu', 'Gwadawa', 'Gwadawi', 'Gwadawo', 'Gwadawu', 'Gwadaya', 'Gwadayi', 'Gwadayo', 'Gwadayu', 'Gwadaza', 'Gwadazi', 'Gwadazo', 'Gwadazu', 'Illela', 'Isa', 'Kaba', 'Kabin', 'Kabjua', 'Kabuje', 'Kabjui', 'Kabjuo', 'Kabjuu', 'Kabjya', 'Kabjye', 'Kabjyi', 'Kabjyo', 'Kabjyu', 'Kabjza', 'Kabjze', 'Kabjzi', 'Kabjzo', 'Kabjzu', 'Kafur', 'Kalgo', 'Kamuran', 'Kanawa', 'Kanwa', 'Kaole', 'Kaou', 'Kaounje', 'Kaounja', 'Kaounse', 'Kaounsere', 'Kaounso', 'Kaounsore', 'Kaouzou', 'Kaowe', 'Kaoweje', 'Kaowenje', 'Kaowensa', 'Kaowenta', 'Kaowera', 'Kaowerda', 'Kaowere', 'Kaoweri', 'Kaowero', 'Kaowesa', 'Kaowese', 'Kaowesi', 'Kaoweso', 'Kaowesu', 'Kaoweta', 'Kaowete', 'Kaoweti', 'Kaoweto', 'Kaowetu', 'Kaowewa', 'Kaowewe', 'Kaowewi', 'Kaowewo', 'Kaowewu', 'Kaoweya', 'Kaoweye', 'Kaoweyi', 'Kaoweyo', 'Kaoweyu', 'Kaoweza', 'Kaoweze', 'Kaowezi', 'Kaowezo', 'Kaowezu'],
  'Taraba': ['Ardo-Kola', 'Balanga', 'Bali', 'Bumbuta', 'Donga', 'Gashaka', 'Gassol', 'Ibi', 'Idu', 'Ijagun', 'Ijigba', 'Ika', 'Ikyodummaa', 'Iyambo', 'Jalingo', 'Katsina-Ala', 'Kawar', 'Lau', 'Sardauna', 'Takum', 'Taraba', 'Wukari', 'Yorro', 'Zing'],
  'Yobe': ['Bade', 'Borsari', 'Damaturu', 'Dapchi', 'Dukku', 'Dundaye', 'Durbar', 'Fada', 'Fakai', 'Fagge', 'Falke', 'Farra', 'Ferenje', 'Gashua', 'Geidam', 'Gujba', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Jigawa', 'Jimbetoto', 'Kaita', 'Kakai', 'Kakare', 'Kakkau', 'Kala', 'Kalo', 'Kamadougou', 'Kamajesu', 'Kamaki', 'Kamalangu', 'Kamalele', 'Kamaleran', 'Kamaleru', 'Kamaletu', 'Kamali', 'Kamalian', 'Kamalib', 'Kamaligara', 'Kamalile', 'Kamaline', 'Kamalini', 'Kamalino', 'Kamalire', 'Kamalisa', 'Kamalisi', 'Kamalita', 'Kamaliti', 'Kamalitu', 'Kamaliwa', 'Kamaliye', 'Kamalizi', 'Kamalobo', 'Kamalolu', 'Kamalomu', 'Kamalona', 'Kamalonje', 'Kamalonja', 'Kamalonjo', 'Kamalope', 'Kamalora', 'Kamalore', 'Kamalori', 'Kamaloro', 'Kamaloru', 'Kamalosa', 'Kamalose', 'Kamalosi', 'Kamaloso', 'Kámalosu', 'Kamalota', 'Kamalote', 'Kamaloti', 'Kamaloto', 'Kamalotu', 'Kamalowa', 'Kamalowe', 'Kamalowi', 'Kamalowo', 'Kamalowu', 'Kamaloya', 'Kamaloye', 'Kamaloyi', 'Kamaloyo', 'Kamaloyu', 'Kamaloza', 'Kamaloze', 'Kamalozi', 'Kamalozo', 'Kamalozu'],
  'Zamfara': ['Anka', 'Bakura', 'Birnin Magaji', 'Bukkuyum', 'Bungudu', 'Chafe', 'Dandume', 'Dansadau', 'Dukku', 'Dundaye', 'Durbar', 'Fada', 'Fakai', 'Fagge', 'Falke', 'Farra', 'Ferenje', 'Gada', 'Gadabuke', 'Gafan', 'Gafara', 'Gafari', 'Gafaru', 'Gafata', 'Gafawa', 'Gafaya', 'Gafaza', 'Gafira', 'Gafiso', 'Gafita', 'Gafiya', 'Gafizu', 'Gafja', 'Gafka', 'Gafla', 'Gafma', 'Gafna', 'Gafni', 'Gafnija', 'Gafnile', 'Gafno', 'Gafnso', 'Gafnta', 'Gafnwa', 'Gafnya', 'Gafnza', 'Gafora', 'Gafore', 'Gafori', 'Gaforo', 'Gaforu', 'Gaforya', 'Gafra', 'Gafre', 'Gafria', 'Gafrija', 'Gafrika', 'Gafrila', 'Gafrika', 'Gafrila', 'Gafrika', 'Gafrila'],
};

export const STATES = Object.keys(NIGERIA_STATES_LGA).sort();

export const getLGAsForState = (state) => {
  return NIGERIA_STATES_LGA[state] || [];
};